(package "flymake-eask"
         "0.1.0"
         "Eask support in Flymake")

(website-url "https://github.com/emacs-eask/flymake-eask")
(keywords "lisp" "eask")

(package-file "flymake-eask.el")

(source "gnu")
(source "melpa")

(depends-on "emacs" "26.1")
(depends-on "flymake-easy")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
